# 网站图标
favicon: "/assets/img/avatar.jpg"
apple_touch_icon: "/assets/img/avatar.jpg"

# 导航栏
navbar:
  blog_title: "BDFFZI的小屋"

# 主页
index:
  # 头图相对页面的占比
  banner_img_height: 50
  slogan:
    text: "笔记 |   分享 |   杂谈"

# 文章页
post:
  # 侧边分类栏
  category_bar:
    # 需要显式启用
    specific: false

  # 评论
  comments:
    enable: true
    type: waline

  # 数学
  math:
    enable: true
    specific: false
    engine: mathjax

waline:
  serverURL: "waline-1-c7584562.deta.app"

# 关于页
about:
  avatar: "/assets/img/avatar.jpg"
  name: "BDFFZI"
  intro: "一切随缘"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/BDFFZI", tip: "GitHub" }
    - { class: "iconfont icon-bilibili-fill", link: "https://space.bilibili.com/35949109", tip: "Bilibili" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/assets/img/wechat.jpg" }

footer:
  # 网页pv和uv统计
  statistics:
    enable: true

custom_css:
  - "/assets/css/content.css"
  - "/assets/css/layout.css"
  - "/assets/css/bilicard.css"

custom_js:
  - "/assets/js/noCache.js"
  - "/assets/js/mermaid.min.js"
  - "/assets/js/enableMermaid.js"
