# 网站图标
favicon: "/assets/img/avatar.jpg"
apple_touch_icon: "/assets/img/avatar.jpg"

# 导航栏
navbar:
  blog_title: "BDFFZI的小屋"
  ground_glass:
    enable: true

# 页脚
footer:
  # 网站pv与uv统计
  statistics:
    enable: false # 由于动不动就要换网址，浏览统计已经失去意义。

# 主页
index:
  # 头图相对页面的占比
  banner_img_height: 40
  slogan:
    text: "笔记 |   分享 |   杂谈"

# 文章页
post:
  # 更新时间
  updated:
    enable: true
  # 侧边分类栏
  category_bar:
    # 需要显式启用
    specific: false
  # 侧边目录
  toc:
    collapseDepth: 2

  # 评论
  comments:
    enable: true
    type: giscus

  # 数学
  math:
    enable: true
    engine: katex

  # 图表
  mermaid:
    enable: true

# 关于页
about:
  avatar: "/assets/img/avatar.jpg"
  name: "BDFFZI"
  intro: "一切随缘"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/BDFFZI", tip: "GitHub" }
    - { class: "iconfont icon-bilibili-fill", link: "https://space.bilibili.com/35949109", tip: "Bilibili" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/assets/img/wechat.jpg" }

# 评论插件
giscus:
  repo: "BDFFZI/Page.Blog"
  repo-id: "R_kgDOLNpbRw"
  category: "Announcements"
  category-id: "DIC_kwDOLNpbR84CjAdm"

# 自定义内容
custom_css:
  - "/assets/css/content.css"
  - "/assets/css/layout.css"
  - "/assets/css/bilicard.css"
custom_js:
  - "/assets/js/noCache.js"
