#网站设置
url: https://bdffzi-blog.pages.dev/
title: BDFFZI的小屋
subtitle:
description: 一个个人博客，用于分享自己的经验杂谈等。
author: BDFFZI
language: zh-CN
timezone: Asia/Shanghai
theme: fluid

#文章设置
permalink: "posts/:abbrlink.html"
new_post_name: ":title.md"
default_layout: draft
index_generator:
  path: ""
  per_page: 10
  order_by: "-date"

# hexo-renderer-markdown-it渲染器（旧渲染器hexo-renderer-marked已移除）
markdown:
  plugins:
    # fluid的latex数学渲染需要的插件
    - name: "@traptitech/markdown-it-katex"
      options:
        strict: "ignore"

# hexo-abbrlink插件
abbrlink:
  alg: crc32
  rep: dec
  drafts: true

# hexo-filter-mermaid-diagrams插件
mermaid:
  enable: true

#未使用
post_asset_folder: false
keywords: null
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ":lang"
skip_render: null
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
deploy:
  type: ""
